baseURL = "https://tushar5526.github.io"
languageCode = "en-us"
title = "Tushar Gupta"
theme = "PaperMod"

googleAnalytics = "G-B043Q33E0E"

[params]
defaultTheme = "auto"

# Shown on the home page
socialIcons = [
  { name = "email", url = "mailto:codingid6+portfolio@gmail.com" },
  { name = "github", url = "https://github.com/tushar5526" },
  { name = "twitter", url = "https://twitter.com/tushar5526" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/12409303/tushar-gupta"},
  { name = "linkedin", url="https://www.linkedin.com/in/tushar55"},
  { name = "other", url="https://drive.google.com/file/d/1Sask75Pd8b-CulTPGIALXDYR0bGi3UBh/view?usp=sharing" }
]

# Configure the home page
[params.profileMode]
enabled = true
title = "Hi, I'm Tushar."
subtitle = "Say hello to me at various places on the internet."

# configure navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "about"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "blog"
name = "blog"
title = "blog"
url = "/blog/"

[[menu.main]]
weight = 2
identifier = "til"
name = "today-i-learned"
title = "til"
url = "/til/"

[[menu.main]]
weight = 2
identifier = "projects-and-oss"
name = "projects-and-oss"
title = "projects-and-oss"
url = "/projects-and-oss/"


[[menu.main]]
weight = 5
identifier = "tags"
name = "tags"
title = "tags"
url = "/tags/"

[taxonomies]
  tag = "tags"

[fuse]
